#!/bin/bash
# Name: acesso.ssh
# Author: Marcos Ferreira da Rocha
# E-Mail: marcos.fr.rocha@gmail.com

# Este script envia automatiza a geração e inserção de chave  pública em um servidor ssh.
# Para ficar mais comodo envie esse arquivo para o diretório /usr/bin
# Uso 
# acesso vyos vyos@192.168.1.1

# Criando o par de chaves
ssh-keygen

# Enviando a chave pública para o servidor
ssh-copy-id "$2"

# Adicionado a função no arquivo .bashrc para facilitar a  autenticaçaõ, o exec $SHELL recarrega a sessaõ para utilizar a nova  função.

echo "$1() { ssh $2; }" >>  .bashrc ;  exec $SHELL
