#!/bin/bash

RETVAL=0
## get mini UID limit ##
_l="/etc/login.defs"
_p="/etc/passwd" ## get mini UID limit ##
l=$(grep "^UID_MIN" $_l) ## get max UID limit ##
l1=$(grep "^UID_MAX" $_l) ## use awk to print if UID >= $MIN and UID <= $MAX and shell is not /sbin/nologin ##

case "$1" in
   "") 
      	echo -e " Uso 
 list [-u| users]  -- Exibe os usuários normais (que não sejam do sistema)   \n
 [-U| users-systems]   -- Exibe todos os usuarios do sistema \n
 [groups|-g ]      -- Exibe grupos criados via addgroup \n
 [all-groups|-G]"  -- Exibe todos os grupos do sistema 



      RETVAL=1
	;;

	users|-u)
     	#awk -F: '/\/home/ && ($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd
#	awk -F':' -v "min=${l##UID_MIN}" -v "max=${l1##UID_MAX}" '{ if ( $3 >= min && $3 <= max ) print $0}' /etc/passwd
	echo "----------[ Normal User Accounts ]---------------"
	awk -F':' -v "min=${l##UID_MIN}" -v "max=${l1##UID_MAX}" '{ if ( $3 >= min && $3 <= max && $7 != "/sbin/nologin" ) print $0 }' "$_p" | cut -f1 -d:

	;;
	users-systems|-U)
	echo "----------[ System User Accounts ]---------------"
	awk -F':' -v "min=${l##UID_MIN}" -v "max=${l1##UID_MAX}" '{ if ( !($3 >= min && $3 <= max && $7 != "/sbin/nologin")) print $0 }' "$_p" | cut -f1 -d:


	;;

	groups|-g)
     	awk -F: '/\/etc/group && ($3 >= 1000)  && ( $3 < 65534) {printf "%s:%s\n",$1,$3}' /etc/group
	;;

	all-groups|-G)
	awk -F:    '{printf "%s:%s\n",$1,$3}' /etc/group
	;;
esac

exit $RETVAL
