#!/bin/bash
# Name: Userlist
# Author: Marcos Ferreira da Rocha
# E-Mail: marcos.fr.rocha@gmail.com

# Sobre: O userlist é um utilitário para listar de forma simples usuários e grupos presentes no sistema.
# Ele confere se estão no diretório /home e no arquivo /etc/password


RETVAL=0

case "$1" in
   "") 
      	echo -e " Uso 
 list [-u| users]  -- Exibe os usuarios criados criados com ferramentas administrativas normalmente  possuiem ID acima de 1000 e que possuam diretório home , exceto o  user nobody  \n
 [-U| all-users]   -- Exibe todos os usuarios do sistema \n
 [groups|-g ]      -- Exibe grupos criados via addgroup \n
 [all-groups|-G]"  -- Exibe todos os grupos do sistema 

      RETVAL=1
	;;

	users|-u)
     	awk -F: '/\/home/ && ($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd
	;;
	all-users|-U)
        awk -F: '{printf "%s:%s\n",$1,$3}' /etc/passwd
	;;

	groups|-g)
     	awk -F: '/\/etc/group && ($3 >= 1000)  && ( $3 < 65534) {printf "%s:%s\n",$1,$3}' /etc/group
	;;

	all-groups|-G)
	awk -F:    '{printf "%s:%s\n",$1,$3}' /etc/group
	;;
esac

exit $RETVAL
