#!/bin/bash
# Name: acesso.ssh
# Author: Marcos Ferreira da Rocha
# E-Mail: marcos.fr.rocha@gmail.com

# Este script envia automatiza a geração e inserção de chave  pública em um servidor ssh.
# Para ficar mais comodo envie esse arquivo para o diretório /usr/bin
# Uso 
# acesso vyos vyos@192.168.1.1


# Criando arquivos de funcao
	DIR=~/.local/share/acesso/
	if [ ! -f $DIR ]; then
           mkdir -p ~/.local/share/acesso
	fi
	FILE=~/.local/share/acesso/access_functions
	if [ ! -f $FILE ]; then
           touch ~/.local/share/acesso/access_functions
	fi

# Funcao

	if [[ "$SHELL" == *"bash"* ]] ;then
			funcao=$(grep -q 'source ~/.local/share/acesso/access_functions' ~/.bashrc && echo $?)
				if [ "$funcao" != "0" ]; then
					echo "source ~/.local/share/acesso/access_functions" >> ~/.bashrc
				fi
	elif [[ "$SHELL" == *"zsh"* ]] ;then
            funcao=$(grep -q 'source ~/.local/share/acesso/access_functions' ~/.zshrc && echo $?)
	            if [ "$funcao" != "0" ]; then
        	    	echo "source ~/.local/share/acesso/access_functions" >> ~/.zshrc
				fi
    else
                  echo "sem shell"
    fi
 ajuda(){
  	cat <<EOF
	Para adicionar um host siga o modelo abaixo
	acesso -a apelido usuario@192.168.1.1
	
	Opções;

	-l --list		Lista as conexões registradas
	-a --add 		Adiciona um nova conexão
	-n --new-key		Cria um novo par de chaves
	-e --edit		edita o arquivo de  conexões
	-h --help		Exibe o menu de ajuda
EOF
}

config(){
	cat <<EOF

	Abaixo é apresentado o conjuto de  diretórios e arquivos que compõem a aplicação

	access_functions	Armazena as conexões registradas
	~/.local/share/acesso/	Armazena os arquivos de configuração da aplicação
	~/.bashrc		Exportar o arquivo access_functions para o shell corrent
	~/.zshrc		Exportar o arquivo access_functions para o shell corrente
	~/.ssh/			Diretório utilizado para  acessar o par de chaves
	/usr/bin/		Diretório com  script executável

EOF
}

RETVAL=0

	case "$1" in
   	"")
		ajuda

	RETVAL=1
		;;
	--new-key|n|-n)

		ssh-keygen
	;;
	--add|-a|a)
	if [[ ! -z "$2"  &&  ! -z "$3" ]]; then 

	# Criando o par de chaves
#		SSH
		chave=~/.ssh/key-acesso.rsa
		if [ ! -f $chave ]; then
			ssh-keygen -t rsa -N '' -f "$chave"
		fi

#		Enviando a chave pública para o servidor
		ssh-copy-id  -i "$chave".pub "$3"

#		Adicionado a função no arquivo .bashrc para facilitar a  autenticaçaõ, o exec $SHELL recarrega a sessaõ para utilizar a nova  função.

		echo "$2() { ssh -i "$chave" "$3"; }" >>  ~/.local/share/acesso/access_functions ; exec $SHELL
	else
		ajuda
	fi
	;;
	--list|-l)
		echo ""
		cat ~/.local/share/acesso/access_functions | sed -e 's/()/  |  /'| sed -e 's/{//' | sed -e 's/}//' | sed -e 's/;/ /'  | sed -e 's/   //'
		echo "" 
	;;
	--edit|-e)
		nano ~/.local/share/acesso/access_functions

	;;
	--conf|-c)
		config
	;;
	--help|-h)
		ajuda	
	esac

exit $RETVAL